schema_version = "1.0.0"
id = "io_scene_bz2msh"
version = "1.1.0"
name = "Battlezone II/CC MSH Importer"
tagline = "Import/Export BZ2/BZCC MSH files with full animation support and intact global/local mesh."
maintainer = "GrizzlyOne95"
type = "add-on"
website = "https://github.com/GrizzlyOne95/io_scene_bz2msh/tree/main"

[blender]
minimum_version = "4.5.0"